name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths: 
      - 'Salidas/**'      
  workflow_dispatch:      

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_MUD_03FA78310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./Salidas" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "." # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

      - name: enviar correo 
        if: failure() || cancelled()
        uses: dawidd6/action-send-mail@v3
        with:
         connection_url: smtp://proyectosbas:${{ secrets.emailpassword }}@mail.bas.com.ar:25
         server_address: mail.bas.com.ar
         server_port: 25 
         secure: false

         from: GitHub <proyectosbas@bas.com.ar>
         to: capacitacion@bas.com.ar
         subject: Error en la actualización en Azure del help de BASCS
         body: |
            Se ha producido un error en la actualización en Azure del help de BASCS.
           
            Commit: ${{github.sha}}
            Autor: ${{github.actor}}
            Mensaje: ${{github.event.head_commit.message}}

         ignore_cert: true
         nodemailerlog: true
         nodemailerdebug: true          

      - name: enviar correo 
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
         connection_url: smtp://proyectosbas:${{ secrets.emailpassword }}@mail.bas.com.ar:25
         server_address: mail.bas.com.ar
         server_port: 25 
         secure: false

         from: GitHub <proyectosbas@bas.com.ar>
         to: capacitacion@bas.com.ar
         subject: Actualización en Azure del help de BASCS
         body: |
            Se ha actualizado exitosamente en Azure el help de BASCS.
           
            Commit: ${{github.sha}}
            Autor: ${{github.actor}}
            Mensaje: ${{github.event.head_commit.message}}

         ignore_cert: true
         nodemailerlog: true
         nodemailerdebug: true          



